-- Create table for tracking attendance (Clock In / Clock Out)
CREATE TABLE IF NOT EXISTS public.attendance_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT NOT NULL, -- e.g. PC Name or authenticated user ID
    event_type TEXT CHECK (event_type IN ('INICIO', 'FIN')) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create table for tracking detailed window activity
CREATE TABLE IF NOT EXISTS public.activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT NOT NULL,
    window_title TEXT,
    duration_seconds INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_attendance_employee_id ON public.attendance_log(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_timestamp ON public.attendance_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_employee_id ON public.activity_log(employee_id);
CREATE INDEX IF NOT EXISTS idx_activity_created_at ON public.activity_log(created_at);

-- Output for confirmation
SELECT 'Tables created successfully' as status;
